### ISSUE TITLE
usage w/ REST API

### ISSUE THREAD

**Issue by fahrulalwan** [walangkaji/ZTE-F609-API#2]
wah thanks banget nih akhirnya ada yang provide api untuk router zte.

btw gue bukan pengguna php, ini bisa diakses pake rest api gak ya?

rencananya gue pengen buat cron job buat ganti password otomatis setiap bulannya sih.

**Comment by walangkaji** [comment]
bisa aja pak kalo tau caranya untuk akses router dari luar jaringan lokal,
kalo punya server yang 1 jaringan dengan modem malah enak biasa langsung dipake.

nanti untuk fungsi ganti password bisa ditambahi, kalo versi sekarang belum ada, karena pada dasarnya belum butuh hehehe
