### ISSUE TITLE
nanya

### ISSUE THREAD

**Issue by ari123mster** [walangkaji/ZTE-F609-API#7]
Undefined property: walangkaji\ZteF609\ZteApi::$debug

gua nyoba dilaravel kok error ya bang message kaya di atas

**Comment by walangkaji** [comment]
full errornya bisa di kasih lihat mas? ada di line berapa?

**Comment by ari123mster** [comment]
line 142 ztef609.php bang

 if ($this->debug) {

            echo "[" . date('h:i:s A') . "]: $function" . str_repeat(' ', $space);

            echo(empty($text) ? '' : ': ' . $text) . PHP_EOL;

        }

    }

**Comment by walangkaji** [comment]
coba install yang latest version mas, sepertinya sudah di benerin

**Comment by ari123mster** [comment]
ok mas saya coba dlu

**Comment by walangkaji** [comment]
siap ditunggu hasilnya mas

**Comment by ari123mster** [comment]
mantap langsung bisa mas

**Comment by ari123mster** [comment]
ini buat php 8 bisa gak mas?

**Comment by walangkaji** [comment]
saya jalanin pake php 8 bisa mas,

**Comment by ari123mster** [comment]
aku coba gak bisa 
coba nnti aku fixin deh
sekalian buat yg f660 v8 mas wkwkwk

**Comment by walangkaji** [comment]
errornya apa bisa di cek mas yang php 8

**Comment by ari123mster** [comment]
datanya gak nampil mas

array []

ini aku test make 2 php
di php7.4 lancar jaya
kalau di php 8.1 datanya null

**Comment by walangkaji** [comment]
[https://i.imgur.com/prIL49b.png](https://i.imgur.com/prIL49b.png) disini masih aman mas pake php 8.1,
untuk f660 v8 saya ga punya modemnya 😄

**Comment by ari123mster** [comment]
siap bang
ini baru ngedevelop 
gabungin api mikrotik + api zte
